name: convert design token to css
on: [push]

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npx token-transformer data/tokens.json input/reference.json reference
      - run: npx token-transformer data/tokens.json input/semantic.json reference,semantic reference
      - run: npx token-transformer data/tokens.json input/component.json reference,semantic,component reference,semantic
      - run: npx style-dictionary build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build tokens
