name: convert design token to css
on: [push]

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npx token-transformer data/tokens.json input/core.json core
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: build tokens
